{
    "channels": [
        "conda-forge"
    ],
    "dependencies": [
        "pip=24.2=pyhd8ed1ab_0",
        "python=3.9.19",
        "conda-pack=0.8.0=pyhd8ed1ab_0",
        "xrootd=5.7.0=py39he65be9b_0",
        "dill=0.3.8=pyhd8ed1ab_0",
        "conda=24.7.1=py39hf3d152e_0",
        {
            "pip": [
                "ttbarEFT",
                "coffea==0.7.22"
            ]
        }
    ],
    "name": "base"
}